global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets:
        - 'prom_1:9090'
        - 'prom_2:9090'

  - job_name: 'node_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.190.118:9100']

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
